### ISSUE TITLE
Double quotes is missing in exp id of Determination of Viscosity Average Molecular Weight of Polymer simulation

### ISSUE THREAD

**Issue by mrudhvika940** [vlabs-on-openedx/open-edx-physical-chemistry-virtual-lab-amrita#1]
Double quotes is missing in exp id of Determination of Viscosity Average Molecular Weight of Polymer simulation

**Comment by sravanthimodepu** [comment]
After updating the above-mentioned exp_id to the experiment, the lab is able to get the analytics usage for all the experiments. Hence closing the issue.
